### ISSUE TITLE
Transaction id

### ISSUE THREAD

**Issue by fayzdeveloper** [datatrans/google-pay-web-sample#2]
sir, I am unable to get the transaction id . Please help

**Comment by oheister** [comment]
It looks like you tried to use the currency INR, which was not active on our side for this test account. Can you please try again?

**Comment by fayzdeveloper** [comment]
Thanks for the response. Its working fine using USD currency. Currency INR
will work fine in production environment right?

**Comment by oheister** [comment]
We support all currencies. The merchants need to inform us which currencies we should configure for them.

**Comment by fayzdeveloper** [comment]
Thank you for your response
